### ISSUE TITLE
Install fails on Archlinux.

### ISSUE THREAD

**Issue by fennecdjay** [samdroid-apps/reddit-is-gtk#59]
I can't build from git either.
Both complain about `snudown/src/markdown.h`, needed from snudown.

**Comment by danalec** [comment]
complain directly to the maintainer: https://aur.archlinux.org/packages/something-for-reddit-git/

**Comment by sylveon** [comment]
Clone `https://github.com/samdroid-apps/snudown` in `src/something-for-reddit/src/snudow` and checkout the branch `something-for-reddit`


Also the package needs to depend on `python2-setuptools` and `gperf` but doesn't, you'll need to install them before building.


Quick patch, in `src/Makefile.am`, change line 46 to point to your pkgdir instead of pointing to the system libdir (there's probably a better solution, but I am too lazy to find it):

    install snudown.so /home/charles/tmp/something-for-reddit-git/pkg/something-for-reddit-git/usr/lib/snudown.so 

Run `makepkg -si`
Install  should succeed, but then crashes on my machine:
```
^_^[Charles Milette@Humble Huckleberry ~/tmp/something-for-reddit-git/src/something-for-reddit]$ reddit-is-gtk
Traceback (most recent call last):
  File "/usr/bin/reddit-is-gtk", line 12, in <module>
    import redditisgtk.main
ModuleNotFoundError: No module named 'redditisgtk'
```

Launching the `something-for-reddit` binary works, however.

**Comment by samdroid-apps** [comment]
I've gone back to using the python based version.  I'm planning to do a bugfix release of that codebase soon.  Therefore, the snudown issues should no longer be there.

Could you check if this still causes issues on Arch @sylveon or @fennecdjay?

Cheers!

**Comment by fennecdjay** [comment]
I hadn't test for a while, but it install flawlessly now, without the snudown problem.
